### PR TITLE
DO NOT MERGE: Homepage to support next feature launch

### PR DESCRIPTION
**Pull request by paulrobertlloyd**
Notes:
* ~~Requires a few updates to the CSS, which I’ve added in a separate PR in the registry repo (see: https://github.com/snyk/registry/pull/2036).~~
* Removed `id`s on CTAs which I suspect are being used for tracking. As the CTAs are all changing, have removed these for now, pending instruction on what names should be used instead.
* Content needs final approval (@guypod, @AH7, @geva)
* Image of updated page shared in Slack.

### CODE REVIEW

**Review by joshje — APPROVED** [review]
LGTM 👍 

I'll let @AH7 comment on whether those IDs are important for any tracking purposes.  I can see that we bind to them and emit analytics data currently:

```
 $(".section-homepage #cta-add-github-repos").on("click", function() {
        var userStatus = getAnalyticsUserStatus();
        analytics.track("Web: GH primary CTA on homepage: " + userStatus, null, {
            integrations: {
                All: false,
                "Amazon S3": true,
                "Keen IO": true
            }
        });
});
$(".section-homepage #cta-signup").on("click", function() {
        var userStatus = getAnalyticsUserStatus();
        analytics.track("Web: Sign up primary CTA on homepage: " + userStatus, null, {
            integrations: {
                All: false,
                "Amazon S3": true,
                "Keen IO": true
            }
        });
});
```

If we're happy for analytics to go to all sources (and not specific ones like above), adding a `data-snyk-track-on-click="Name of your event here"` is a nicer (cleaner) way to track things

**Review by AH7 — APPROVED** [review]

**Comment by joshje** [comment]
@paulrobertlloyd I'd suggest adding a `data-snyk-track-on-click="Name of your event here"` to any new CTA's you want analytics for.

I can add those if you'd like.

**Comment by AH7** [comment]
@joshje for the homepage I think having events for each of the CTA like we had 'Web: Sign up primary CTA on homepage' would be sufficient.

**Comment by joshje** [comment]
@paulrobertlloyd LMK if you need a hand with this

**Comment by paulrobertlloyd** [comment]
@joshje Sorry, distracted. Looking at this now!

**Review by joshje — APPROVED** [review]

**Pull request merged**
